# ============================================================================
# BLOG REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-11-14 11:54:23 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.blog import BlogUpdate, BlogCreate, BlogOut

async def create_blog(blog_data: BlogCreate) -> BlogOut:
    blog_dict = blog_data.model_dump()
    result =await db.blogs.insert_one(blog_dict)
    result = await db.blogs.find_one(filter={"_id":result.inserted_id})
    returnable_result = BlogOut(**result)
    return returnable_result

async def get_blog(filter_dict: dict) -> Optional[BlogOut]:
    try:
        result = await db.blogs.find_one(filter_dict)

        if result is None:
            return None

        return BlogOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching blog: {str(e)}"
        )
    
async def get_blogs(filter_dict: dict = {},start=0,stop=100) -> List[BlogOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.blogs.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        blog_list = []

        async for doc in cursor:
            blog_list.append(BlogOut(**doc))

        return blog_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching blogs: {str(e)}"
        )
async def update_blog(filter_dict: dict, blog_data: BlogUpdate) -> BlogOut:
    result = await db.blogs.find_one_and_update(
        filter_dict,
        {"$set": blog_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = BlogOut(**result)
    return returnable_result

async def delete_blog(filter_dict: dict):
    return await db.blogs.delete_one(filter_dict)